### ISSUE TITLE
Why is the eval needed?

### ISSUE THREAD

**Issue by rugk** [zubfatal/php-session-cleaner#3]
eval does not sound so nice. ;)

Can't it be avoided? 

Actually Debians default cron script (in `/usr/lib/php5/sessionclean`) does it like this: 

``` sh
find -O3 "$save_path" -depth -mindepth 1 -name 'sess_*' -ignore_readdir_race -type f -cmin "+$gc_maxlifetime" -delete
```

**Comment by zubfatal** [comment]
It **could** but without it, it will throw an error if the path doesn't exist or there are no files to process.
